app/models.py
from . import db,login_manager
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash


class User(db.Model,UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255),unique= True,nullable=False)
    username =db.Column(db.String(255),unique =True,nullable=False)
    password_hash = db.Column(db.String())
    blog=db.relationship('Blog', backref='user', lazy='dynamic')
    comment=db.relationship('Comment', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)
        # print(check_password_hash,"eeeeeeeeeeeeee")
        
    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.add(self)
        db.session.commit()

    def __repr__ (self):
        return 'User{self.username}'
        
class Blog(db.Model):
    __tablename__ = 'blog'

    id=db.Column(db.Integer,primary_key=True)
    post= db.Column(db.String(255),nullable= False)
    title = db.Column(db.String(255),nullable= False)
    time=db.Column(db.DateTime,default=datetime.utcnow)
    category= db.Column(db.String(255),nullable=False)
    user_id= db.Column(db.Integer,db.ForeignKey('users.id'))
    comment=db.relationship('Comment', backref='blog',lazy='dynamic')

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    def __repr__ (self):
        return 'Blog{self.post}'

class Comment(db.Model):
    __tablename__ = 'comment'

    id=db.Column(db.Integer,primary_key=True)
    content=db.Column(db.String(255),nullable=False)
    time=db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    blog_id = db.Column(db.Integer,db.ForeignKey('blog.id'))

    def save_comments(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,blog_id):
        comments= Comment.query.filter_by(blod_id= blog_id).all()


    def __repr__(self):
        return 'Comment:{self.content}'


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_login import LoginManager
from flask_bootstrap import Bootstrap


db = SQLAlchemy()
login_manager = LoginManager()
bootstap = Bootstrap()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    db.init_app(app)
    bootstap.init_app(app)
    login_manager.init_app(app)
    login_manager.session_protection = 'strong'
    login_manager.login_view = 'auth.login'
    login_manager.login_message = "You must be logged in to access this page."

    

    #registering blueprints
    from .auth import auth as authentication_blueprint
    app.register_blueprint(authentication_blueprint)

    from .main import main as main_blueprint 
    app.register_blueprint(main_blueprint)
    
    return app

app/main/__init__.py
from flask import Blueprint
main=Blueprint('main',__name__)
from .views import *

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required,current_user
from ..models import User,Comment,Blog
from .. import db
from .form import BlogForm,CommentForm
@main.route('/')
def index():
    blog = Blog.query.all()
    news= Blog.query.filter_by(category='news')
    technology = Blog.query.filter_by(category='Technology').all
    sports=Blog.query.filter_by(category='Sports').all
    music=Blog.query.filter_by(category='Music').all
    
    return render_template('index.html', news=news,technology=technology,music=music,blog=blog,sports=sports)


@main.route('/blog',methods=['GET','POST'])
@login_required
def new_blog():
    form=BlogForm()
    if form.validate_on_submit():
        title=form.title.data
        category=form.category.data
        post=form.post.data
        user_id=current_user
        
        new_blog_object = Blog(post=post,title=title,category=category,user_id=current_user._get_current_object().id)
        new_blog_object.save_blog()
        return redirect(url_for('main.index'))
    return render_template('blog.html', form=form)



@main.route('/comment/<int:blog_id>', methods=['GET','POST'])
@login_required
def comment(blog_id):
    form=CommentForm()
    blog= Blog.query.get(blog_id)
    all_comments=Comment.query.filter_by(blog_id=blog_id).all()
    if form.validate_on_submit():
        comment=form.content.data
        blog_id=blog_id
        user_id = current_user._get_current_object().id
        new_comment= Comment(comment=comment,user_id=user_id,blog_id=blog_id)
        new_comment.save_comment()
        return redirect(url_for('.comment',blog_id=blog_id))
    return render_template('comment.html',form=form,blog=blog,all_comments=all_comments)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    user_id = current_user._get_current_object().id
    posts = Blog.query.filter_by(user_id=user_id).all()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bloggers</title>
</head>
{% block styles %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">
{% endblock %}
<body>
    {% block navbar %}
        {% include "navbar.html" %}
        {% endblock %}
        {% block content %}
        
        {% endblock %}
</body>
</html>

app/templates/blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h2 class="text-center">Create your Blog Here</h2>
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{%endblock%}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        {% if all_comments %}
        <div class="col-lg-12 col-md-12 col-sm-12">
            <h4 class="text-center">All Comment</h4>
            {% for comment in all comments %}
            <div class="card w-90 mb-3">
                <div class="card-body">
                    <h5>{{ comment.blog.title }}</h5>
                    <p class="card-title">{{comment.content}}</p>
                    <p class="card-text">----{{comment.user.username}}----</p>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'macro.html' as macro %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="welcome">
                      <div class="head text-ccenter">
                        <h1 class="display-4 text-center mes mt-5" >AMJAAN'S BLOG</h1>
                        
                    </div>          
            </div>
        </div>
    </div>
<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12">
  <div class="jumbotron jumbotron-fluid mt-4">
      <h1 class="display-4 text-center" >MY BLOGS</h1>
  </div>
</div>
</div>
<div class="row">
    <!-- <div class="col-md-12 col-lg-12 col-sm-12 p-2 blog"> -->
            {% for blog_post in blog %}
            <div class="card p-3 ml-3 mt-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">{{ blog_post.title}}</h5>
                  <h5 class="card-title">{{ blog_post.category}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Posted By:{{ blog_post.user.username}}</h6>
                  <p class="card-text">{{ blog_post.post}}</p>
                  <a href="{{url_for('main.new_blog')}}" class="card-link">Create Blog</a>
                  <button type="button" class="btn btn-primary btn-lg">{{blog_post.time}}</button>

                </div>
              </div>
              {% endfor %}
    </div>
</div>
</div>
{% endblock %}

app/templates/navbar.html
{%block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav navbar-right">
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.index')}}" style="color: white;"><strong>HOME</strong></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.register')}}" ><strong>SIGN UP</strong></a>
        </li>
        {%if current_user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}"><strong>PROFILE</strong></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.logout')}}"><strong>LOGOUT</strong></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.new_blog')}}"><strong>CREATE A BLOG</strong></a>
        </li>
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}"><strong>LOGIN</strong></a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{%block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-body text-center">
                  <h5 class="card-title"> <h3> {{user.username| capitalize}} </h3>
                  </h5>
                  <h6 class="card-subtitle mb-2 text-muted">{{user.email}}</h6>
                  <p class="card-text">{{user.blog.title}} </p>
                  <a href="{{url_for('main.index')}}" class="card-link">HOME</a>
                </div>
              </div>
        </div>
        </div>
</div>


  {%endblock%}